import { createElement } from 'lwc';
import Temp from 'c/temp';

describe('c-temp', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {

        const element = createElement('c-temp', {
            is: Temp
        });

        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});